spring:  
  cloud:
    gateway:
      routes:
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: PRODUCT-SERVICE
#                fallbackuri: forward:/productServiceFallBack
                
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payments/**
#           filters:
#            - name: CircuitBreaker
#              args:
#                name: PAYMENT-SERVICE
#                fallbackuri: forward:/paymentServiceFallBack
                
        - id: CART-SERVICE
          uri: lb://CART-SERVICE
          predicates:
            - Path=/carts/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: PAYMENT-SERVICE
#                fallbackuri: forward:/paymentServiceFallBack
       
   
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
